# 01_03. Numpy

Numerical Python의 약자인 Numpy는 Python에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 하는 패키지입니다.<br>
기존의 Python Array는 Array간 연산을 하기 위해 loop를 사용하여 계산해야 하는데, 대용량 데이터를 연산하게 된다면 아무래도 속도가 느릴 수 밖에 없습니다.<br>
따라서 조금 더 low-level의 언어인 C/C++ 기반으로 만들어져서 대용량 데이터를 빠르게 연산할 수 있게 하는 Numpy가 많이 쓰이게 됩니다.<br>
이 말은 성능이 좋은 C/C++ 기반의 코드를 Numpy로 호출해서 통합할 수 있다는 의미이기도 합니다.

## 01. Numpy의 중요성

Numpy는 방대한 기능을 지원하고 있기에, 마스터하기 까지는 상당한 시간과 코딩 경험이 필요합니다.<br>
하지만 머신러닝 알고리즘이나 과학, 통계 지원용 패키지를 개발하지 않는 이상 Numpy를 상세히 알 필요는 없습니다.<br>

그럼에도 불구하고 Numpy를 이해해야 하는 이유는 간단합니다.<br>
대부분의 머신러닝 알고리즘이 Numpy로 이루어져 있는 만큼 모델의 입, 출력 데이터가 Numpy를 사용하기 때문입니다.<br>
ML에서 대부분의 경우 더 향상된 패키지인 Pandas를 사용하고, 앞으로 정리되는 내용에도 Pandas가 사용될 예정이지만, Pandas 패키지 내부에서도 Numpy를 사용하고 있는 만큼 어느정도의 이해가 필요하다고 할 수 있습니다.

아래부터는 자주 사용되는 Numpy API에 대해 정리할 예정입니다.

## 02. ndarray

Numpy의 ndarray에 대해 학습합니다.<br>
먼저 Numpy 패키지를 불러오는 코드를 실행합니다.<br>

Numpy는 보통 `np`로 줄여서 많이 씁니다.

In [2]:
import numpy as np

ndarray는 다차원 배열을 생성하고, 각 배열을 연산하는데 사용됩니다.<br>
Numpy와 ndarray에서 자주 쓰이는 내장함수는 다음과 같습니다.
- `np.array()` : python 리스트와 같은 다양한 인자를 받아 ndarray로 형변환 합니다.
- `shape`: ndarray의 차원을 확인하는데 사용합니다.

In [3]:
# 1차원 배열
arr1 = np.array([1, 2, 3])
print(f"arr1 type: {type(arr1)}")
print(f"arr1 shape: {arr1.shape}")

# 2차원 배열: 2행 3열
arr2 = np.array([[1, 2, 3],
                 [2, 3, 4]])
print(f"arr2 type: {type(arr2)}")
print(f"arr2 shape: {arr2.shape}")

# 2차원 배열: 1행 3열
arr3 = np.array([[1, 2, 3]])
print(f"arr3 type: {type(arr3)}")
print(f"arr3 shape: {arr3.shape}")

arr1 type: <class 'numpy.ndarray'>
arr1 shape: (3,)
arr2 type: <class 'numpy.ndarray'>
arr2 shape: (2, 3)
arr3 type: <class 'numpy.ndarray'>
arr3 shape: (1, 3)


ndarray의 차원을 이해하는 것은 ML에서 중요합니다.<br>
왜냐하면 ML의 알고리즘에서 요구하는 입출력 데이터가 어떤 차원의 데이터를 요구하는지가 각자 다르기 때문입니다.<br>
이 경우 `reshape()` 함수를 사용하여 차원을 재정의 할 수 있지만 일단 여기서는 다루지 않겠습니다.

ndarray의 차원을 확인하는 변수는 `ndim`입니다.<br>
위에서 선언한 변수 `arr1`, `arr2`, `arr3`의 차원을 확인해보겠습니다.

In [4]:
print(f"arr1 dimension: {arr1.ndim}")
print(f"arr2 dimension: {arr2.ndim}")
print(f"arr3 dimension: {arr3.ndim}")

arr1 dimension: 1
arr2 dimension: 2
arr3 dimension: 2


## 03. ndarray의 데이터 타입

ndarray에 넣을 수 있는 데이터의 타입은 숫자, 문자열, Bool 등 모두 가능합니다.<br>
이 중 숫자형에 해당하는 타입은 다음과 같습니다.
   - int (8, 16, 32)
   - uint (8, 16, 32)
   - float (16, 32, 64, 128)
   - complex

ndarray 내부에 있는 데이터 타입은 `dtype` 변수로 확인이 가능합니다.

In [8]:
list1 = [1, 2, 3]
print(type(list1))

arr1 = np.array(list1)
print(type(arr1))
print(f"{arr1}, {arr1.dtype}")

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3], int64


만약 ndarray에 다른 데이터 타입을 초기화 한다면, 가장 큰 데이터 타입으로 자동 형변환 시켜줍니다.

In [9]:
# int, str 혼합
list2 = [1, 2, "test"]
arr2 = np.array(list2)
print(f"{arr2}, {arr2.dtype}")

# int, float 혼합
list3 = [1, 2, 3.0]
arr3 = np.array(list3)
print(f"{arr3}, {arr3.dtype}")

['1' '2' 'test'], <U21
[1. 2. 3.], float64


ndarray는 명시적 형변환도 가능합니다.<br>
자료형의 byte에 따라 연산 효율에 차이가 나는데, 가령 float 데이터를 int로 연산해도 될 때 형변환을 해서 사용하게 됩니다.<br>
이 경우 `astype()` 함수를 사용하여 형변환 합니다.

In [11]:
# int형 ndarray 선언
arr_int = np.array([1, 2, 3])
# float으로 일괄 형변환
arr_float = arr_int.astype("float64")
print(f"{arr_float}, {arr_float.dtype}")

# int로 다시 일괄 형변환
arr_int1 = arr_float.astype("int32")
print(f"{arr_int1}, {arr_int1.dtype}")

# float형 ndarray 선언
arr_float1 = np.array([1.1, 2.1, 3.1])
# int로 강제 형변환 -> 자동으로 내림 연산이 수행됩니다.
arr_int2 = arr_float1.astype("int32")
print(f"{arr_int2}, {arr_int2.dtype}")

[1. 2. 3.], float64
[1 2 3], int32
[1 2 3], int32


## 04. ndarray 초기화 - arange, zeros, ones

특정 크기와 차원을 가진 ndarray를 연속값, 0, 1로 모두 초기화 하여 빠르게 생성할 수 있습니다.

### arange()

연속값을 초기화 할 때 사용하며 주로 쓰는 parameter는 다음과 같습니다.
- start: 시작값
- stop: 마지막 값 - 1

In [13]:
seq_arr = np.arange(start=0, stop=10)
# 혹은
## seq_arr = np.arange(10)

print(f"{seq_arr}")
print(f"{seq_arr.dtype}\t{seq_arr.shape}\t{seq_arr.ndim}")

[0 1 2 3 4 5 6 7 8 9]
int64	(10,)	1


### zeros(), ones()

두 함수 모두 튜플 형태의 shape를 넣어주면 그 shape 대로 0이나 1값을 초기화하여 반환합니다.<br>
주로 쓰는 parameter는 다음과 같습니다.
- dtype: ndarray의 데이터 타입<br>
    default 값은 float64 입니다.

In [15]:
zero_arr = np.zeros((3, 2), dtype="int32")
print(zero_arr)
print(f"{zero_arr.dtype}\t{zero_arr.shape}\t{zero_arr.ndim}")

one_arr = np.ones((4, 5))
print(one_arr)
print(f"{one_arr.dtype}\t{one_arr.shape}\t{one_arr.ndim}")

[[0 0]
 [0 0]
 [0 0]]
int32	(3, 2)	2
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64	(4, 5)	2
