# 01_03. Numpy

Numerical Python의 약자인 Numpy는 Python에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 하는 패키지입니다.<br>
기존의 Python Array는 Array간 연산을 하기 위해 loop를 사용하여 계산해야 하는데, 대용량 데이터를 연산하게 된다면 아무래도 속도가 느릴 수 밖에 없습니다.<br>
따라서 조금 더 low-level의 언어인 C/C++ 기반으로 만들어져서 대용량 데이터를 빠르게 연산할 수 있게 하는 Numpy가 많이 쓰이게 됩니다.<br>
이 말은 성능이 좋은 C/C++ 기반의 코드를 Numpy로 호출해서 통합할 수 있다는 의미이기도 합니다.

## 01. Numpy의 중요성

Numpy는 방대한 기능을 지원하고 있기에, 마스터하기 까지는 상당한 시간과 코딩 경험이 필요합니다.<br>
하지만 머신러닝 알고리즘이나 과학, 통계 지원용 패키지를 개발하지 않는 이상 Numpy를 상세히 알 필요는 없습니다.<br>

그럼에도 불구하고 Numpy를 이해해야 하는 이유는 간단합니다.<br>
대부분의 머신러닝 알고리즘이 Numpy로 이루어져 있는 만큼 모델의 입, 출력 데이터가 Numpy를 사용하기 때문입니다.<br>
ML에서 대부분의 경우 더 향상된 패키지인 Pandas를 사용하고, 앞으로 정리되는 내용에도 Pandas가 사용될 예정이지만, Pandas 패키지 내부에서도 Numpy를 사용하고 있는 만큼 어느정도의 이해가 필요하다고 할 수 있습니다.

아래부터는 자주 사용되는 Numpy API에 대해 정리할 예정입니다.

## 02. ndarray

Numpy의 ndarray에 대해 학습합니다.<br>
먼저 Numpy 패키지를 불러오는 코드를 실행합니다.<br>

Numpy는 보통 `np`로 줄여서 많이 씁니다.

In [2]:
import numpy as np

ndarray는 다차원 배열을 생성하고, 각 배열을 연산하는데 사용됩니다.<br>
Numpy와 ndarray에서 자주 쓰이는 내장함수는 다음과 같습니다.
- `np.array()` : python 리스트와 같은 다양한 인자를 받아 ndarray로 형변환 합니다.
- `shape`: ndarray의 차원을 확인하는데 사용합니다.

In [3]:
# 1차원 배열
arr1 = np.array([1, 2, 3])
print(f"arr1 type: {type(arr1)}")
print(f"arr1 shape: {arr1.shape}")

# 2차원 배열: 2행 3열
arr2 = np.array([[1, 2, 3],
                 [2, 3, 4]])
print(f"arr2 type: {type(arr2)}")
print(f"arr2 shape: {arr2.shape}")

# 2차원 배열: 1행 3열
arr3 = np.array([[1, 2, 3]])
print(f"arr3 type: {type(arr3)}")
print(f"arr3 shape: {arr3.shape}")

arr1 type: <class 'numpy.ndarray'>
arr1 shape: (3,)
arr2 type: <class 'numpy.ndarray'>
arr2 shape: (2, 3)
arr3 type: <class 'numpy.ndarray'>
arr3 shape: (1, 3)


ndarray의 차원을 이해하는 것은 ML에서 중요합니다.<br>
왜냐하면 ML의 알고리즘에서 요구하는 입출력 데이터가 어떤 차원의 데이터를 요구하는지가 각자 다르기 때문입니다.<br>
이 경우 `reshape()` 함수를 사용하여 차원을 재정의 할 수 있지만 일단 여기서는 다루지 않겠습니다.

ndarray의 차원을 확인하는 변수는 `ndim`입니다.<br>
위에서 선언한 변수 `arr1`, `arr2`, `arr3`의 차원을 확인해보겠습니다.

In [4]:
print(f"arr1 dimension: {arr1.ndim}")
print(f"arr2 dimension: {arr2.ndim}")
print(f"arr3 dimension: {arr3.ndim}")

arr1 dimension: 1
arr2 dimension: 2
arr3 dimension: 2


## 03. ndarray의 데이터 타입

ndarray에 넣을 수 있는 데이터의 타입은 숫자, 문자열, Bool 등 모두 가능합니다.<br>
이 중 숫자형에 해당하는 타입은 다음과 같습니다.
   - int (8, 16, 32)
   - uint (8, 16, 32)
   - float (16, 32, 64, 128)
   - complex

ndarray 내부에 있는 데이터 타입은 `dtype` 변수로 확인이 가능합니다.

In [5]:
list1 = [1, 2, 3]
print(type(list1))

arr1 = np.array(list1)
print(type(arr1))
print(f"{arr1}, {arr1.dtype}")

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3], int64


만약 ndarray에 다른 데이터 타입을 초기화 한다면, 가장 큰 데이터 타입으로 자동 형변환 시켜줍니다.

In [6]:
# int, str 혼합
list2 = [1, 2, "test"]
arr2 = np.array(list2)
print(f"{arr2}, {arr2.dtype}")

# int, float 혼합
list3 = [1, 2, 3.0]
arr3 = np.array(list3)
print(f"{arr3}, {arr3.dtype}")

['1' '2' 'test'], <U21
[1. 2. 3.], float64


ndarray는 명시적 형변환도 가능합니다.<br>
자료형의 byte에 따라 연산 효율에 차이가 나는데, 가령 float 데이터를 int로 연산해도 될 때 형변환을 해서 사용하게 됩니다.<br>
이 경우 `astype()` 함수를 사용하여 형변환 합니다.

In [7]:
# int형 ndarray 선언
arr_int = np.array([1, 2, 3])
# float으로 일괄 형변환
arr_float = arr_int.astype("float64")
print(f"{arr_float}, {arr_float.dtype}")

# int로 다시 일괄 형변환
arr_int1 = arr_float.astype("int32")
print(f"{arr_int1}, {arr_int1.dtype}")

# float형 ndarray 선언
arr_float1 = np.array([1.1, 2.1, 3.1])
# int로 강제 형변환 -> 자동으로 내림 연산이 수행됩니다.
arr_int2 = arr_float1.astype("int32")
print(f"{arr_int2}, {arr_int2.dtype}")

[1. 2. 3.], float64
[1 2 3], int32
[1 2 3], int32


## 04. ndarray 초기화 - arange, zeros, ones

특정 크기와 차원을 가진 ndarray를 연속값, 0, 1로 모두 초기화 하여 빠르게 생성할 수 있습니다.

### arange()

연속값을 초기화 할 때 사용하며 주로 쓰는 parameter는 다음과 같습니다.
- start: 시작값
- stop: 마지막 값 - 1

In [8]:
seq_arr = np.arange(start=0, stop=10)
# 혹은
## seq_arr = np.arange(10)

print(f"{seq_arr}")
print(f"{seq_arr.dtype}\t{seq_arr.shape}\t{seq_arr.ndim}")

[0 1 2 3 4 5 6 7 8 9]
int64	(10,)	1


### zeros(), ones()

두 함수 모두 튜플 형태의 shape를 넣어주면 그 shape 대로 0이나 1값을 초기화하여 반환합니다.<br>
주로 쓰는 parameter는 다음과 같습니다.
- dtype: ndarray의 데이터 타입<br>
    default 값은 float64 입니다.

In [9]:
zero_arr = np.zeros((3, 2), dtype="int32")
print(zero_arr)
print(f"{zero_arr.dtype}\t{zero_arr.shape}\t{zero_arr.ndim}")

one_arr = np.ones((4, 5))
print(one_arr)
print(f"{one_arr.dtype}\t{one_arr.shape}\t{one_arr.ndim}")

[[0 0]
 [0 0]
 [0 0]]
int32	(3, 2)	2
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64	(4, 5)	2


## 05. ndarray의 차원 변경 - reshape()

원본 shape를 원하는 shape로 변경할 때 사용합니다.<br>
당연한 얘기이지만, 원본 shape에서 변형해서 만들 수 없는 모양으로 변경은 할 수 없습니다.<br>
따라서 이런 경우를 방지하기 위해 보통은 인자로 -1를 넣어서 자동으로 만들어 줄 수 있게 합니다.

In [15]:
# 0~99까지의 길이 100의 1차원 배열 생성
arr1 = np.arange(100)
print(f"arr1 =\n{arr1}")

# 2차원 배열로 reshape
# index가 100개이므로, 2x50이 가능합니다.
arr2 = arr1.reshape(2, 50)
print(f"arr2 =\n{arr2}")

# 만약 길이가 너무 길어서 10x? 형태로 만들어야 한다면 -1을 사용합니다.
arr3 = arr2.reshape(10, -1)
print(f"arr3 =\n{arr3}")

arr1 =
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
arr2 =
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
  98 99]]
arr3 =
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### 가장 많이 사용되는 shape는?

ndarray의 연산은 차원 중 1이 있다면 항상 연산이 가능하므로, `(-1, 1)` 형태의 reshape를 많이 쓰게됩니다.

In [21]:
arr1 = np.arange(50)
# 1차원 배열을 3차원으로 변환
arr1_3d = arr1.reshape(2, -1, 5)

print(f"arr1 shape = {arr1.shape}")
print(f"arr1_3d shape = {arr1_3d.shape}")

# 차원이 맞지 않으므로, 이 코드는 Value Error
# arr1 + arr1_3d

# 차원수 맞추기
arr1_2d = arr1.reshape(-1, 1)
arr1_3d_2d = arr1_3d.reshape(-1, 1)
print(f"arr1_2d shape = {arr1_2d.shape}")
print(f"arr1_2d =\n{arr1_2d}")
print(f"arr1_3d_2d shape = {arr1_3d_2d.shape}")
print(f"arr1_3d_2d =\n{arr1_3d_2d}")

# 같은 값이므로, 값을 2제곱하는 결과가 출력됩니다.
result = arr1_2d * arr1_3d_2d
print(f"result shape = {result.shape}")
print(f"result =\n{result}")

arr1 shape = (50,)
arr1_3d shape = (2, 5, 5)
arr1_2d shape = (50, 1)
arr1_2d =
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]
 [37]
 [38]
 [39]
 [40]
 [41]
 [42]
 [43]
 [44]
 [45]
 [46]
 [47]
 [48]
 [49]]
arr1_3d_2d shape = (50, 1)
arr1_3d_2d =
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]
 [37]
 [38]
 [39]
 [40]
 [41]
 [42]
 [43]
 [44]
 [45]
 [46]
 [47]
 [48]
 [49]]
result shape = (50, 1)
result =
[[   0]
 [   1]
 [   4]
 [   9]
 [  16]
 [  25]
 [  36]
 [  49]
 [  64]
 [  81]
 [ 100]
 [ 121]
 [ 144]
 [ 169]
 [ 196]
 [ 225]
 [ 256]
 [ 289]
 [ 324]
 [ 361]
 [ 400]
 [ 441]
 [ 484]
 [ 529]
 [ 576]
 [ 625]
 [ 676]
 [ 729]
 [ 784]
 [ 841]
 [ 900]

## 06. ndarray의 indexing

ndarray에서 특정 값이나 범위의 배열을 참조하거나 활용해야 할 때 사용합니다.<br>
목적은 다음과 같습니다.
- 특정 index의 데이터만 추출해야 할 때
- 특정 범위의 데이터만 추출해야 할 때
- Fancy Indexing: 특정 index 값들에 해당하는 데이터만 추출해야 할 때
- Boolean Indexing: 조건에 해당하는 데이터만 추출해야 할 때

### 단일 값 추출

1개의 데이터를 가져오려면 차원수에 맞게 해당 index값을 가져오면 됩니다.<br>
가져온 데이터의 Data type은 해당 nparray의 dtype에 해당하는 값을 가져오게 됩니다.

인덱스는 음수를 지정할 수도 있는데, 이렇게 지정하면 뒤에서부터 데이터를 가져오게 됩니다.

In [25]:
arr1 = np.arange(start=5, stop=22)
print(f"arr1 =\n{arr1}")
print(f"arr1 dtype = {arr1.dtype}")

# 17값을 가져오고 싶다면?
# 17 - 5 = 12
value = arr1[12]
print(f"value = {value}")
print(f"value type = {type(value)}")

# arr1의 마지막에서 2번째 값을 확인하고 싶다면?
value = arr1[-2]
print(f"value = {value}")
print(f"value type = {type(value)}")

arr1 =
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
arr1 dtype = int64
value = 17
value type = <class 'numpy.int64'>
value = 20
value type = <class 'numpy.int64'>


또한 단일 index로도 값을 수정할 수 있습니다.

In [26]:
arr1[-1] = 1
print(f"arr1 =\n{arr1}")

arr1 =
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20  1]


n차원의 데이터를 가져오려면 `,`를 사용하여 해당 차원 인덱스에 접근할 수 있습니다.

In [29]:
# 3차원 데이터로 reshape
arr1 = np.arange(100)
arr1_3d = arr1.reshape(2, 5, -1)
print(f"arr1_3d =\n{arr1_3d}")

print(f"1, 4, 3 인덱스의 값: {arr1_3d[1, 4, 3]}")

arr1_3d =
[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]]

 [[50 51 52 53 54 55 56 57 58 59]
  [60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]
1, 4, 3 인덱스의 값: 93


#### Axis
ndarray에서 행, 열로 보이기는 하지만, 이 개념은 사실 ndarray에서 통용되는 해석은 아닙니다.<br>
ndarray에서 이 개념을 설명할 때는 `axis`라는 개념으로 해석됩니다.

행의 방향, 열의 방향, 높이를 예시로 들면 각각 axis는 0, 1, 2가 됩니다.<br>
3차원 이상의 ndarray에서는 이 axis에 대한 연산을 지원하기 때문에 기억해 두면 좋습니다.

### 범위 값 추출

`:` 기호를 사용해 연속 데이터를 추출할 수 있습니다.<br>
단일 index 값을 가져오는 것과 마찬가지로, index의 범위를 지정하면 해당하는 범위의 ndarray를 가져옵니다.<br>
값을 생략하고 바로 `:`를 사용하면 이후에 있는 모든 값을 가져오게 됩니다.<br>
만약 모든 index를 생략한다면, 전체 범위를 의미하게 됩니다.

In [32]:
arr1 = np.arange(start=1, stop=10)
arr2 = arr1[0:3]
arr3 = arr1[:-2]
arr4 = arr1[:]

print(f"arr1 =\n{arr1}")
print(f"arr2 =\n{arr2}")
print(f"arr3 =\n{arr3}")
print(f"arr4 =\n{arr4}")

arr1 =
[1 2 3 4 5 6 7 8 9]
arr2 =
[1 2 3]
arr3 =
[1 2 3 4 5 6 7]
arr4 =
[1 2 3 4 5 6 7 8 9]


#### 다차원 배열의 slicing

단일 값을 불러오는 것과 마찬가지로 사용합니다.<br>
slicing을 하면서 단일 index를 사용할 수도 있습니다.<br>
다음은 3차원 배열의 값을 slicing해서 가져오는 예시입니다.

In [37]:
arr1 = np.arange(0, 20)
arr2 = arr1.reshape(2, 5, -1)

print(f"arr2 =\n{arr2}")
print(f"arr2 shape: {arr2.shape}")

# 1. axis=0의 1번 index부터 마지막 index 까지
# 2. axis=1의 뒤에서 2번째 부터 마지막 index 까지
# 3. axis=2의 모든 index
arr3 = arr2[1:, -2:, :]
# 1. axis=0의 0번 index
# 2. axis=1의 0번부터 4번까지
# 3. axis=2의 1번 index
arr4 = arr2[0, :4, 1]
print(f"arr3 =\n{arr3}")
print(f"arr3 shape: {arr3.shape}")
print(f"arr4 =\n{arr4}")
print(f"arr4 shape: {arr4.shape}")

arr2 =
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
arr2 shape: (2, 5, 2)
arr3 =
[[[16 17]
  [18 19]]]
arr3 shape: (1, 2, 2)
arr4 =
[1 3 5 7]
arr4 shape: (4,)


#### 차원 축소

N차원 배열에서 slicing 범위를 하나만 지정하게 된다면, N-1차원의 배열이 출력됩니다.

In [38]:
arr5 = arr2[0]
print(f"arr5 =\n{arr5}")
print(f"arr5 shape: {arr5.shape}")

arr5 =
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
arr5 shape: (5, 2)


### Fancy Indexing

특정 index의 집합으로 배열을 slicing 합니다.<br>
만약 0, 1, 5, 7 index의 값을 배열로서 가져오고 싶다면, Fancy Indexing을 사용하여 가져올 수 있습니다.

In [39]:
arr1 = np.arange(start=1, stop=10)
arr1_2d = arr1.reshape(3, -1)
print(f"arr1_2d =\n{arr1_2d}")

# 1. axis=0 의 0, 1번째 index에 속하는 배열 중
# 2. axis=1의 2번째 index
arr3 = arr1_2d[[0, 1], 2]
print(f"arr3 =\n{arr3}")
print(f"arr3 shape: {arr3.shape}")

arr1_2d =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr3 =
[3 6]
arr3 shape: (2,)


### Boolean Indexing

조건이 참이라면, 그 index의 값을 가져옵니다.<br>
데이터를 다루다보면 조건에 따라 값을 분류하는 상황이 자주 나오기 때문에, 가장 많이 사용하는 방식의 slicing이 아닐까 싶습니다.<br>
해당 위치에 조건이 True 라면, 그 위치의 값을 가져옵니다.

In [44]:
arr1 = np.arange(start=1, stop=10)
arr1_2d = arr1.reshape(3, 3)
print(f"arr1_2d =\n{arr1_2d}")
print(f"arr1_2d shape: {arr1_2d.shape}")

# 2의 배수인 배열
# 차원 축소가 발생하므로 1차원 배열로 출력됩니다.
mask = arr1_2d % 2 == 0
arr2 = arr1_2d[mask]
print(f"mask =\n{mask}")
print(f"arr2 =\n{arr2}")
print(f"arr2 shape: {arr2.shape}")

arr1_2d =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr1_2d shape: (3, 3)
mask =
[[False  True False]
 [ True False  True]
 [False  True False]]
arr2 =
[2 4 6 8]
arr2 shape: (4,)
